version: "3.9"

services:
  app:
    image: damirpilacis/app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'npm test'
    volumes:
      - ".env.example:/app/.env"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
      - DATABASE_HOST=db

  db:
    image: postgres
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
