services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - "./app:/app"
    depends_on:
      db:
        condition: service_healthy
  caddy:
    image: caddy 
    ports:
      - "1800:80"
      - "443:443"
    volumes: 
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
  db:
    extends:
      file: docker-compose.yml
      service: db
