version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    command: bash -c 'sleep 4 && npm start'
    depends_on:
      db-dev:
        condition: service_healthy
    volumes:
      - "./app:/app"
  caddy:
    image: caddy 
    ports:
      - "1800:80"
      - "443:443"
    volumes: 
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
  db-dev:
    extends:
      file: docker-compose.yml
      service: db
