services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    command: npm run dev
    volumes:
      - "./app:/app"
  caddy:
    image: caddy 
    ports:
      - "1800:80"
      - "443:443"
    volumes: 
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
