version: "3.9"

services:
  app:
    image: damirpilacis/app
    build: 
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'npm test'
    depends_on:
      db:
        condition: service_healthy
  db: 
    image: postgres
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
