jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make test

  image-push:
    steps:
      - uses: actions/checkout@v3
      - run: make image-push
    needs: test
